# Generated by Django 4.2.16 on 2024-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_notes_recipe_pic_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(default='TBD', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(default='No description has been added to this recipe.', help_text='Add notes or a description here.'),
        ),
    ]
