# Generated by Django 4.2.16 on 2024-10-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_difficulty_alter_recipe_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
